# Uncomment the next line to define a global platform for your project
platform :ios, '12'

target 'IdentitySdkDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IdentitySdkDemo
  pod 'IdentitySdkCore', :path => '../IdentitySdkCore'
end
